services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER:      ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:        ${POSTGRES_DB:-scrummy_word_count}
    volumes:
      - pg:/var/lib/postgresql/data
      - ./scripts/database-setup:/docker-entrypoint-initdb.d

volumes:
  pg:
