services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER:      ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:        ${POSTGRES_DB:-scrummy_word_count}

      MOMO_PWD: ${MOMO_PWD:-secret1}
      JAMIE_PWD: ${JAMIE_PWD:-secret2}
      ANDERS_PWD: ${ANDERS_PWD:-secret3}
      SERVICE_PWD: ${SERVICE_PWD:-serviceSecret}

    volumes:
      - pg:/var/lib/postgresql
      - ./scripts/database-setup:/docker-entrypoint-initdb.d
      - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf

    command: >
      postgres
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c password_encryption=scram-sha-256

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOTNET_USE_POLLING_WATCHER: 1
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: true
      DOTNET_RUNNING_IN_CONTAINER: true

      ConnectionStrings__ScrummyWordCountDB: ${POSTGRES_CONNECTION_STRING:-Host=postgres;Port=5432;Database=scrummy_word_count;Username=postgres;Password=postgres}
    volumes:
      - ./Source:/Source

      # Override the bin and obj folders to support hot reloading
      - /Source/ScrummyWordCountApi/bin
      - /Source/ScrummyWordCountApi/obj

      - /Source/ScrummyWordCountApiTests/bin
      - /Source/ScrummyWordCountApiTests/obj
    ports:
      - "5012:5012"
    command: dotnet watch run --no-hot-reload -v normal --project Source/ScrummyWordCountApi/ScrummyWordCountApi.csproj --urls http://0.0.0.0:5012

volumes:
  pg:
